### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by levy002** [levy002/doctors_appointment_back_end#17]
### Hello reviewer :wave:

Our team has 3 members:
  - @direakanbi 
  - @ridaarif98 
  - @levy002 

We have created the Kanban board for this project
    check it [here](https://github.com/users/levy002/projects/3/views/1).
![image](https://user-images.githubusercontent.com/87197412/184157972-950237b8-56e7-4491-b567-6c0aa5b5066a.png)

database design
![image](https://user-images.githubusercontent.com/87197412/184314525-0b7a39cf-a7cd-4d40-b802-a32613bbc73e.png)

### Thank you for reviewing our issue.

**Comment by MuriloRoque** [comment]
Hi @levy002, @tmampa, @ridaarif98, @direakanbi,

Good job so far!
There are some issues that you still need to work on but you are almost there!

## Suggested changes

- [ ] Please put a screenshot of your Kanban board to this issue's description, as it says in the requirements.

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MuriloRoque** [comment]
Hi @levy002, @tmampa, @ridaarif98, @direakanbi,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
